[build]
  command = """
    pip install -r requirements.txt && \
    python process_thumbnails.py && \
    gem update --system && \
    gem install bundler -v 2.4.22 && \
    bundle _2.4.22_ install && \
    bundle exec jekyll build
  """
  publish = "_site"

[build.environment]
  RUBY_VERSION = "2.7.2"